{{- range $gnbId:=.Values.gnbIds }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}-{{$gnbId}}
  labels:
    {{- include "oai-gnb-multi.labels" (list $ $gnbId) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "oai-gnb-multi.selectorLabels" (list $ $gnbId) | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-gnb-multi.selectorLabels" (list $ $gnbId) | nindent 8 }}
        app: oai-gnb-multi
    spec:
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
    {{- if $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml $.Values.imagePullSecrets | indent 8 }}
    {{- end }}
    {{- if $.Values.global }}{{ if $.Values.global.waitForAMF }}
      initContainers:
        - name: init
          image: docker.io/oaisoftwarealliance/oai-tcpdump-init:alpine-3.20
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - until ncat -zv {{ $.Values.config.amfhost }} 38412 --sctp ; do echo waiting for oai-amf to start; sleep 1; done
          resources:
            requests:
              memory: 50Mi
              cpu: 1m
            limits:
              memory: 50Mi
              cpu: 1m
    {{- end }}{{ end }}
      containers:
      - name: gnb-{{$gnbId}}
        image: "{{ $.Values.nfimage.repository }}:{{ $.Values.nfimage.version }}"
        imagePullPolicy: {{ $.Values.nfimage.pullPolicy }}
        securityContext:
          {{- toYaml $.Values.securityContext | nindent 12 }}
        volumeMounts:
          - mountPath: /opt/oai-gnb/etc
            name: configuration-{{$gnbId}}
          - mountPath: /opt/oai-ran
            name: source
            # subPath: gnb.conf
        {{- if $.Values.resources.define}}
        resources:
          requests:
            memory: {{ $.Values.resources.requests.nf.memory | quote }}
            cpu: {{ $.Values.resources.requests.nf.cpu | quote }}
          # limits:
          #   memory: {{ $.Values.resources.limits.nf.memory | quote }}
          #   cpu: {{ $.Values.resources.limits.nf.cpu | quote }}
        {{- end}}
        ports:
        - containerPort: 2152
          name: n3
          protocol: UDP
        - containerPort: 36412
          name: n2
          protocol: SCTP
        command: [ "/bin/bash", "-c" ]
        args:
         -  AMF_IP_ADDRESS=$(getent hosts $AMF_HOST | awk '{print $1}');
            AMF_IP_ADDRESS=$(if [[ $AMF_IP_ADDRESS ]]; then echo $AMF_IP_ADDRESS; else echo $AMF_HOST;fi);
            N2_IP_ADDRESS=$(ip -f inet addr show $N2_IF_NAME | grep -o "inet [0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*");
            N3_IP_ADDRESS=$(ip -f inet addr show $N3_IF_NAME | grep -o "inet [0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*");
            sed -e s/@N2_IP_ADDRESS@/$N2_IP_ADDRESS/g
                -e s/@N3_IP_ADDRESS@/$N3_IP_ADDRESS/g
                -e s/@AMF_IP_ADDRESS@/$AMF_IP_ADDRESS/g
                /opt/oai-gnb/etc/gnb.conf | tee /tmp/gnb.conf;
          {{- if $.Values.start.gnb}}
            exec /opt/oai-ran/cmake_targets/ran_build/build/nr-softmodem -O /tmp/gnb.conf $USE_ADDITIONAL_OPTIONS;
          {{- else}}
            exec /bin/sleep infinity
          {{- end}}
        env:
          - name: GNB_ID
            value: "{{ $gnbId }}"
          - name: TZ
            value: {{ $.Values.config.timeZone }}
          - name: USE_ADDITIONAL_OPTIONS
          {{- if $.Values.config.l2Fapi }}
            value: {{ $.Values.config.l2FapiAdditionalOpts }}
          {{- else}}
            value: {{ $.Values.config.useAdditionalOptions }}
          {{- end}}
          - name: AMF_HOST
            value: {{ $.Values.config.amfhost }}
          - name: N2_IF_NAME
            value: {{ $.Values.config.n2IfName }}
          - name: N3_IF_NAME
            value: {{ $.Values.config.n3IfName }}
      {{- if $.Values.includeTcpDumpContainer }}
      - name: tcpdump
        image: "{{ $.Values.tcpdumpimage.repository }}:{{ $.Values.tcpdumpimage.version }}"
        imagePullPolicy: {{ $.Values.tcpdumpimage.pullPolicy }}
        {{- if $.Values.resources.define}}
        resources:
          requests:
            memory: {{ $.Values.resources.requests.tcpdump.memory | quote }}
            cpu: {{ $.Values.resources.requests.tcpdump.cpu | quote }}
          limits:
            memory: {{ $.Values.resources.limits.tcpdump.memory | quote }}
            cpu: {{ $.Values.resources.limits.tcpdump.cpu | quote }}
        status:
          qosClass: Guaranteed
        {{- end}}
        securityContext:
           capabilities:
              add:
               - NET_ADMIN
               - NET_RAW
              drop:
               - ALL
        {{- if $.Values.start.tcpdump}}
        command:
          - /bin/sh
          - -c
          - /usr/bin/tcpdump -i any -w /tmp/pcap/{{ $.Chart.Name }}_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
      {{- end }}
      volumes:
      - configMap:
          name: {{ $.Chart.Name }}-{{$gnbId}}-configmap
        name: configuration-{{$gnbId}}
      - hostPath:
          type: Directory
          path: {{ $.Values.config.oaiCodePath }}
        name: source
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: {{ $.Values.serviceAccount.name }}
      terminationGracePeriodSeconds: {{ $.Values.terminationGracePeriodSeconds }}
      {{- if $.Values.nodeSelector}}
      nodeSelector: 
         {{- toYaml $.Values.nodeSelector | nindent 12 }}
      {{- end }}
      {{- if $.Values.nodeName}}
      nodeName: {{ $.Values.nodeName }}
      {{- end }}
{{- end }}
